# SPDX-FileCopyrightText: 2025 Friedrich von Never <friedrich@fornever.me>
#
# SPDX-License-Identifier: MIT

---
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.docker
    version: 4.8.5
  - name: community.general
    version: 11.4.2
