# SPDX-FileCopyrightText: 2025 Friedrich von Never <friedrich@fornever.me>
#
# SPDX-License-Identifier: MIT

---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.docker
    version: 3.7.0
