# SPDX-FileCopyrightText: 2025 Friedrich von Never <friedrich@fornever.me>
#
# SPDX-License-Identifier: MIT

---
- name: Configure Certbot for certificate renewal
  hosts: xmpp2
  become: true

  tasks:
    - name: Install certbot
      community.general.snap:
        name: certbot
        classic: true

    # One-time setup should be performed manually, see the documentation:
    # https://certbot.eff.org/instructions?ws=nginx&os=snap&tab=standard
    #
    # sudo certbot --nginx -d codingteam.org.ru -d loglist.xyz -d www.loglist.xyz
    #
    # Verify the changes to the web server configuration files performed by this command.
    #
    # Further updates are done by snap.certbot.renew.timer — see `systemctl list-timers` for details.
