# SPDX-FileCopyrightText: 2025 Friedrich von Never <friedrich@fornever.me>
#
# SPDX-License-Identifier: MIT

---
- name: Main site for codingteam.org.ru
  hosts: xmpp2
  become: true

  vars:
    codingteam_org_ru_version: v1.2.1

  handlers:
    - name: Prune Docker
      community.docker.docker_prune:
        containers: true
        images: true
        images_filters:
          dangling: false
        networks: true
        volumes: true
        builder_cache: true

    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded

  tasks:
    - name: Set up the Docker container
      community.docker.docker_container:
        name: codingteam.org.ru
        image_name_mismatch: recreate
        image: codingteam/codingteam.org.ru:{{ codingteam_org_ru_version }}
        published_ports:
          - 80:5000
        restart_policy: unless-stopped
        default_host_ip: ''
      notify: Prune Docker

    - name: Set up the nginx configuration file
      ansible.builtin.copy:
        src: nginx/conf.d/codingteam.org.ru.conf
        dest: /etc/nginx/conf.d/codingteam.org.ru.conf
        mode: "u=rx,go=rx"
      notify: Reload nginx

    - name: Create a directory for the old logs # uploaded manually
      ansible.builtin.file:
        path: /opt/codingteam/old-logs
        state: directory
        owner: www-data
        group: www-data
        mode: "u=rx,go=rx"
