# SPDX-FileCopyrightText: 2025 Friedrich von Never <friedrich@fornever.me>
#
# SPDX-License-Identifier: MIT

---
- name: Install and configure Nginx
  hosts: xmpp2
  become: true

  handlers:
    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install nginx package
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Remove the *-enabled and *-available directories
      ansible.builtin.file:
        path: "/etc/nginx/{{ item }}"
        state: absent
      loop:
        - modules-available
        - modules-enabled
        - sites-available
        - sites-enabled

    - name: Set up the main nginx configuration file
      ansible.builtin.copy:
        src: nginx/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: Reload nginx
