# SPDX-FileCopyrightText: 2025 Friedrich von Never <friedrich@fornever.me>
#
# SPDX-License-Identifier: MIT

---
- name: Install and configure Nginx
  hosts: xmpp2
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install nginx package
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Start and enable nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
