# SPDX-FileCopyrightText: 2023-2025 Friedrich von Never <friedrich@fornever.me>
#
# SPDX-License-Identifier: MIT

apiVersion: v1
kind: Service
metadata:
  name: ctor
spec:
  ports:
  - nodePort: 32603
    port: 80
  selector:
    app: ctor
  type: NodePort
